# .github/workflows/publish.yml

name: Publish NPM Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "*"

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ubuntu-latest
      uses: actions/setup-node@v2
      with:
        node-version: "lts/*"
    - run: npm ci

  publish-to-chromatic:
    runs-on: ubuntu-latest
    name: Publish to Chromatic
    steps:
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.UI_GITHUB_TOKEN }}

  semantic-release-versioning:
    runs-on: ubuntu-latest
    name: Semantic Release Versioning
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
