# .github/workflows/publish.yml

name: Publish Package

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

jobs:
  initialize:
    runs-on: ubuntu-latest
    name: Initialize
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm ci
      - name: Set NPM token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
   
  publish-to-chromatic:
    runs-on: ubuntu-latest
    name: Publish to Chromatic
    needs: [initialize]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  semantic-release-versioning:
    runs-on: ubuntu-latest
    name: Semantic Release Versioning
    needs: [initialize]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.UI_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.UI_GITHUB_TOKEN }}
