# .github/workflows/publish.yml

name: Publish NPM Package

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

jobs:
  publish-to-chromatic:
    runs-on: ubuntu-latest
    name: Publish to Chromatic
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  semantic-release-versioning:
    runs-on: ubuntu-latest
    name: Semantic Release Versioning
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm semantic-release
