# .github/workflows/publish.yml

name: Publish NPM Package

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

jobs:
  initialize: 
    runs-on: ubuntu-latest
    name: Initilaize
    steps:
       - name: Install Dependencies
         run: npm ci
       - name: Build Package
         run: npm run build --if-present
  publish-to-chromatic:
    runs-on: ubuntu-latest
    name: Publish to Chromatic
    needs: [initialize]
    steps:
      - uses: actions/checkout@v1
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  semantic-release-versioning:
    runs-on: ubuntu-latest
    name: Semantic Release Versioning
    needs: [initialize]
    steps:
      - uses: actions/checkout@v1
      - name: Release
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.UI_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.UI_GITHUB_TOKEN }}
   
