# .github/workflows/publish.yml

name: Publish Package

on:
  push:
    branches: [main]
  pull_request:

jobs:
  initialize:
    runs-on: ubuntu-latest
    name: Initialize
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present

  # release:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: "16.x"
  #     - run: npm ci
  #     - run: npm run build --if-present
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.UI_GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-to-chromatic:
    runs-on: ubuntu-latest
    name: Publish to Chromatic
    needs: [initialize]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  # semantic-release-versioning:
  #   runs-on: ubuntu-latest
  #   name: Semantic Release Versioning
  #   needs: [initialize]
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Release
  #       run: npx semantic-release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.UI_GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #         NODE_AUTH_TOKEN: ${{ secrets.UI_GITHUB_TOKEN }}
